#!/bin/bash
# inv_launch.sh — Launch one analyst in a dedicated tmux session for bug investigation
#
# Usage: inv_launch.sh <executor> <analyst_name> <prompt_dir> [project_dir] [source_conv_id]
#
# executor:      cc | codex | gemini | deepseek
# analyst_name:  code_analyst | logic_analyst
# prompt_dir:    ~/.bug-investigations/{inv_id}/{analyst_name}/ or .../rebuttal/{analyst_name}/
#                Must contain prompt.txt (generated by inv_prepare.sh)
# project_dir:   optional working directory for CC (default: /tmp)
# source_conv_id: optional AG conversation ID for bidirectional linkage
#
# Execution records are stored in ~/.task-delegate/{task_id}/ (centralized).
# This is a thin wrapper around task-delegate/scripts/task_launch.sh.

set -euo pipefail

EXECUTOR="${1:?Usage: inv_launch.sh <executor> <analyst_name> <prompt_dir> [project_dir] [source_conv_id]}"
ANALYST_NAME="${2:?Usage: inv_launch.sh <executor> <analyst_name> <prompt_dir> [project_dir] [source_conv_id]}"
PROMPT_DIR="${3:?Usage: inv_launch.sh <executor> <analyst_name> <prompt_dir> [project_dir] [source_conv_id]}"
PROJECT_DIR="${4:-/tmp}"
SOURCE_CONV="${5:-}"

# Derive inv_id from prompt_dir
# Support: ~/.bug-investigations/{inv_id}/{analyst}/ or .../rebuttal/{analyst}/
INV_ID=$(echo "$PROMPT_DIR" | grep -oP 'bug-investigations/\K[^/]+')

# Check if this is a rebuttal round
IS_REBUTTAL=false
if echo "$PROMPT_DIR" | grep -q '/rebuttal/'; then
  IS_REBUTTAL=true
fi

# Build timestamp-first task_id
INV_TS=$(echo "$INV_ID" | grep -oP '\d{8}_\d{4}')
if [[ "$IS_REBUTTAL" == "true" ]]; then
  TASK_ID="${INV_TS}_inv_rebuttal_${ANALYST_NAME}"
  SESSION="inv-${INV_ID}-reb-${ANALYST_NAME}"
else
  TASK_ID="${INV_TS}_inv_${ANALYST_NAME}"
  SESSION="inv-${INV_ID}-${ANALYST_NAME}"
fi

# Create task-delegate directory and copy prompt
TASK_DELEGATE_TASK_DIR="${HOME}/.task-delegate/${TASK_ID}"
mkdir -p "$TASK_DELEGATE_TASK_DIR"
cp "${PROMPT_DIR}/prompt.txt" "${TASK_DELEGATE_TASK_DIR}/prompt.txt"

# Locate task-delegate launcher
SKILL_DIR="$(cd "$(dirname "$0")" && pwd)"
TASK_DELEGATE_DIR="$(dirname "$SKILL_DIR")/../task-delegate/scripts"
# Also check canonical path
if [[ ! -f "${TASK_DELEGATE_DIR}/task_launch.sh" ]]; then
  TASK_DELEGATE_DIR="/home/lgj/agent-skills/task-delegate/scripts"
fi
TASK_LAUNCH="${TASK_DELEGATE_DIR}/task_launch.sh"

if [[ ! -f "$TASK_LAUNCH" ]]; then
  echo "ERROR: task_launch.sh not found at ${TASK_LAUNCH}" >&2
  echo "Ensure task-delegate skill is installed." >&2
  exit 1
fi

# Post-run hook: reuse panel_extract_output.sh (same format)
POST_RUN_DIR="/home/lgj/agent-skills/agent-panel-discussion/scripts"
POST_RUN="${POST_RUN_DIR}/panel_extract_output.sh"
if [[ ! -f "$POST_RUN" ]]; then
  echo "WARN: panel_extract_output.sh not found, output extraction will be skipped" >&2
  POST_RUN=""
fi

# Extra record fields
EXTRA_RECORD="{\"inv_id\": \"${INV_ID}\", \"analyst\": \"${ANALYST_NAME}\", \"is_rebuttal\": ${IS_REBUTTAL}, \"output_file\": \"${TASK_DELEGATE_TASK_DIR}/output.md\"}"

# Codex fallback to Gemini
FALLBACK_ARG=""
if [[ "$EXECUTOR" == "codex" ]]; then
  FALLBACK_ARG="--fallback gemini"
fi

# Source conversation linkage
SOURCE_ARG=""
if [[ -n "$SOURCE_CONV" ]]; then
  SOURCE_ARG="--source ${SOURCE_CONV}"
fi

# Build post-run arg
POST_RUN_ARG=""
if [[ -n "$POST_RUN" ]]; then
  POST_RUN_ARG="--post-run ${POST_RUN}"
fi

# Launch via task-delegate
bash "$TASK_LAUNCH" \
  "$TASK_ID" \
  "$PROJECT_DIR" \
  --backend "$EXECUTOR" \
  --session "$SESSION" \
  --role "$ANALYST_NAME" \
  --done-marker "INV_DONE" \
  --extra-record "$EXTRA_RECORD" \
  $FALLBACK_ARG \
  $SOURCE_ARG \
  $POST_RUN_ARG

# Output task_id for tracking
echo ""
echo "[inv-launch] task_id=${TASK_ID}"
echo "[inv-launch] execution_dir=${TASK_DELEGATE_TASK_DIR}"
echo "[inv-launch] session=${SESSION}"
