#!/bin/bash
# panel_launch.sh — Launch one agent in a dedicated tmux session for panel discussion
#
# Usage: panel_launch.sh <executor> <agent_name> <prompt_dir> [project_dir] [source_conv_id]
#
# executor:      cc | gemini | codex | deepseek
# agent_name:    skeptic | pragmatist | optimist (used for session naming + role)
# prompt_dir:    ~/.panel-discussions/{panel_id}/round_N/{agent_name}/
#                Must contain prompt.txt (generated by panel_prepare.sh)
# project_dir:   optional working directory (default: /tmp)
# source_conv_id: optional AG conversation ID for bidirectional linkage
#
# Fallback: if codex is unavailable, automatically falls back to gemini
#
# Execution records are stored in ~/.task-delegate/{task_id}/ (centralized).
# The prompt_dir only contains the prompt generated by panel_prepare.sh.
#
# This is a thin wrapper around task-delegate/scripts/task_launch.sh.

set -euo pipefail

EXECUTOR="${1:?Usage: panel_launch.sh <executor> <agent_name> <prompt_dir> [project_dir] [source_conv_id]}"
AGENT_NAME="${2:?Usage: panel_launch.sh <executor> <agent_name> <prompt_dir> [project_dir] [source_conv_id]}"
PROMPT_DIR="${3:?Usage: panel_launch.sh <executor> <agent_name> <prompt_dir> [project_dir] [source_conv_id]}"
PROJECT_DIR="${4:-/tmp}"
SOURCE_CONV="${5:-}"

# Derive panel_id and round from prompt_dir path
# Support: ~/.panel-discussions/{panel_id}/round_N/{agent}/
PANEL_ID=$(echo "$PROMPT_DIR" | grep -oP '(?:panel-discussions|panel)/\K[^/]+')
ROUND_NUM=$(echo "$PROMPT_DIR" | grep -oP 'round_\K\d+')

# Build timestamp-first task_id: extract YYYYMMDD_HHMM from panel_id (panel_YYYYMMDD_HHMM)
PANEL_TS=$(echo "$PANEL_ID" | grep -oP '\d{8}_\d{4}')
TASK_ID="${PANEL_TS}_panel_r${ROUND_NUM}_${AGENT_NAME}"

SESSION="panel-${PANEL_ID}-r${ROUND_NUM}-${AGENT_NAME}"

# Create task-delegate directory and copy prompt
TASK_DELEGATE_TASK_DIR="${HOME}/.task-delegate/${TASK_ID}"
mkdir -p "$TASK_DELEGATE_TASK_DIR"
cp "${PROMPT_DIR}/prompt.txt" "${TASK_DELEGATE_TASK_DIR}/prompt.txt"

# Locate task-delegate launcher
SKILL_DIR="$(cd "$(dirname "$0")" && pwd)"
TASK_DELEGATE_DIR="$(dirname "$SKILL_DIR")/../task-delegate/scripts"
# Also check symlinked .agent/skills path
if [[ ! -f "${TASK_DELEGATE_DIR}/task_launch.sh" ]]; then
  TASK_DELEGATE_DIR="/home/lgj/agent-skills/task-delegate/scripts"
fi
TASK_LAUNCH="${TASK_DELEGATE_DIR}/task_launch.sh"

if [[ ! -f "$TASK_LAUNCH" ]]; then
  echo "ERROR: task_launch.sh not found at ${TASK_LAUNCH}" >&2
  echo "Ensure task-delegate skill is installed." >&2
  exit 1
fi

# Post-run hook: extract output.md from live.log
POST_RUN="${SKILL_DIR}/panel_extract_output.sh"

# Extra record fields for panel context
EXTRA_RECORD="{\"panel_id\": \"${PANEL_ID}\", \"round\": ${ROUND_NUM}, \"output_file\": \"${TASK_DELEGATE_TASK_DIR}/output.md\"}"

# Determine fallback
FALLBACK_ARG=""
if [[ "$EXECUTOR" == "codex" ]]; then
  FALLBACK_ARG="--fallback gemini"
fi

# Build --source arg if provided
SOURCE_ARG=""
if [[ -n "$SOURCE_CONV" ]]; then
  SOURCE_ARG="--source ${SOURCE_CONV}"
fi

# Session resume: for R1+, find prior round's session_id to enable incremental communication
RESUME_ARG=""
if [[ "$ROUND_NUM" -gt 0 ]]; then
  PREV_ROUND=$((ROUND_NUM - 1))
  PREV_TASK_ID="${PANEL_TS}_panel_r${PREV_ROUND}_${AGENT_NAME}"
  PREV_RECORD="${HOME}/.task-delegate/${PREV_TASK_ID}/execution_record.json"
  if [[ -f "$PREV_RECORD" ]] && command -v python3 &>/dev/null; then
    PREV_SESSION=$(python3 -c "
import json
d = json.load(open('${PREV_RECORD}'))
print(d.get('session_id', ''))
" 2>/dev/null || true)
    if [[ -n "$PREV_SESSION" ]]; then
      RESUME_ARG="--resume-session ${PREV_SESSION}"
      echo "[panel-launch] Resuming session from R${PREV_ROUND}: ${PREV_SESSION}"
    else
      echo "[panel-launch] No session_id in R${PREV_ROUND} record, starting fresh session"
    fi
  else
    echo "[panel-launch] No R${PREV_ROUND} execution record for ${AGENT_NAME}, starting fresh session"
  fi
fi

# Launch via task-delegate (execution records go to ~/.task-delegate/{task_id}/)
bash "$TASK_LAUNCH" \
  "$TASK_ID" \
  "$PROJECT_DIR" \
  --backend "$EXECUTOR" \
  --session "$SESSION" \
  --role "$AGENT_NAME" \
  --post-run "$POST_RUN" \
  --extra-record "$EXTRA_RECORD" \
  --done-marker "PANEL_DONE" \
  $FALLBACK_ARG \
  $SOURCE_ARG \
  $RESUME_ARG

# Output task_id for manifest tracking
echo ""
echo "[panel-launch] task_id=${TASK_ID}"
echo "[panel-launch] execution_dir=${TASK_DELEGATE_TASK_DIR}"
